### ISSUE TITLE
Clothes disappear from girl after H event.

### ISSUE THREAD

**Issue by AdaBallard** [ManlyMarco/KK_SkinEffects#5]
It seems to happen if clothes were in off or half-off state during the H event. This results with a girl participated in H event walk away with no clothes. Clothes come back again when you press "Next" (so the game time moves to midday or evening).

This wasn't happening with v1.6.1.

Please fix it.

**Comment by ManlyMarco** [comment]
If you undress the girl in a H scene then she should still be undressed after H scene ends, that's intended. If she's dressed then she should stay dressed. The girl should then go take a shower and the clothes to return then.

You can turn this off in plugin settings, look for clothes persistence.
