### ISSUE TITLE
My girls body gets dark

### ISSUE THREAD

**Issue by MoNnArK69** [ManlyMarco/KK_SkinEffects#6]
Hello, please I need help, I have a big problem that nobody has been able to help me solve. It happens that when I spy on a NPC to masturbate and she reaches the excitement her body becomes dark and the same happens when I first penetrate her. Someone told me that I have a problem with the KK_SkinEffects.dll, because when I delete it from my BepInEx folder from my game that problem does not happen but I want to have those effects (tears, sweat, bleeding). I hope you can help me find the solution. Thanks in advance and I will be attentive to your response
P.D. I have updated these 3 .ddl with the latest versions: KKAPI v1.4.0.1, Koikatsu Overlay Mods v5.0.1 and KK_SkinEffects v1.6.2

![porqueami1](https://user-images.githubusercontent.com/54358894/63432641-85267180-c3ef-11e9-99fd-829410d062fa.png)
![porqueami](https://user-images.githubusercontent.com/54358894/63432673-94a5ba80-c3ef-11e9-9528-4174123947bd.png)

**Comment by ManlyMarco** [comment]
Hello!

This is a rare known issue, I've never been able to reproduce it.

Can you try setting this as a body overlay in character maker? ![SweatBody](https://user-images.githubusercontent.com/39247311/63439523-82973c80-c42e-11e9-92ec-b6aa3b41b2af.png) Then save the card and try loading it in the free H mode. Does the bug happen immediately then?

**Comment by MoNnArK69** [comment]
I'm sorry, but I don't know how to use any editor

**Comment by ManlyMarco** [comment]
Main menu > create > female > body tab > overlays

**Comment by MoNnArK69** [comment]
That folder must be within the root of the game ??? because my game has all these folders and I can't find that folder
![carpetas](https://user-images.githubusercontent.com/54358894/63447537-333f1500-c40a-11e9-9409-758048a3a86d.png)

**Comment by MoNnArK69** [comment]
All those steps should I follow in the game maker?
![maker](https://user-images.githubusercontent.com/54358894/63449194-9a11fd80-c40d-11e9-9168-ed49d8bde270.png)
![maker1](https://user-images.githubusercontent.com/54358894/63449208-9e3e1b00-c40d-11e9-86ed-8e4428ebef45.png)
![maker2](https://user-images.githubusercontent.com/54358894/63449408-14db1880-c40e-11e9-9a76-783ee8f79122.png)

**Comment by ManlyMarco** [comment]
Yes, set this image as body overlay texture, save the character and use this character in extras > free h in main menu.

**Comment by MoNnArK69** [comment]
I already did it, the NPC by default already appears with its drops of sweat (due to what you told me to do), but the problem appears again when the NPC reaches the excitation marker (image No. I sent). As I see this bug appears when the NPC changes from "state", to excited (such as when masturbating, image No. 1 sent) or to pain (when it is penetrated). It seems something sequential that is already installed in the game, I don't know if there is a diagnostic program to run it and see what processes are activated or deactivated during these scenes

**Comment by ManlyMarco** [comment]
I see, thank you for the info. Can you tell me what CPU, GPU and how much RAM do you have?

For now you can fix this by disabling all effects. Go to plugin settings and search for additional skin effects, then turn off all of the options starting with Enable.

**Comment by MoNnArK69** [comment]
[DxDiag.txt](https://github.com/ManlyMarco/KK_SkinEffects/files/3526782/DxDiag.txt)

**Comment by MoNnArK69** [comment]
and all this is what my game includes
[output_log.txt](https://github.com/ManlyMarco/KK_SkinEffects/files/3526800/output_log.txt)

**Comment by MoNnArK69** [comment]
I did not install any other mod, I left it as the repack and updates come

**Comment by ManlyMarco** [comment]
Can you check if this build changes anything?
[KK_SkinEffects.zip](https://github.com/ManlyMarco/KK_SkinEffects/files/3527425/KK_SkinEffects.zip)

**Comment by MoNnArK69** [comment]
I just have to replace this .dll file inside my BepInEx folder, right?

**Comment by MoNnArK69** [comment]
I guess it's modified, because I have that version of KK_skinEffects

**Comment by MoNnArK69** [comment]
IT WORKED!!! Thank you very much, it is working perfectly with all the effects; bleeding, sweat and tears. I repeat, THANK YOU for taking time to help me correct this problem that apparently only I had. I will be very aware of your contributions and now I know where to go if a good "technical support" is required. You're my new hero without a cape, see you soon Manly-san

**Comment by MoNnArK69** [comment]
![LargeSelfishCaimanlizard-size_restricted](https://user-images.githubusercontent.com/54358894/63473853-ff351580-c444-11e9-9162-b84b8cb86d2d.gif)

**Comment by ManlyMarco** [comment]
Good to hear that!
